title: "beeNotice's blog"
description: "Yet Another Technical blog about Java, Distributed Systems and Data"
baseurl: ""
url: "http://beenotice.github.io/"
github_username: beeNotice

# Build settings
markdown: kramdown
